###
POST http://localhost:3001/order HTTP/1.1
Content-Type: application/json
{
    "id_timestamp": "5f7d8c5aefa7c5f7d8c5c5aefa7",
    "name": "order2",
    "items": [
        {
            "id_db": "5f7d8c5aefa7c5f7d8c5aefa7",
            "name": "item2",
            "price": 15,
            "units": 4
        }
    ]
}

###
DELETE http://localhost:3001/order/6411282bbe5ae54a74436f81 HTTP/1.1


###
GET http://localhost:3001/daysales  HTTP/1.1

###
GET http://localhost:3001/daysales/5f7d8c5aefa7c5f7d8c5aefa7  HTTP/1.1

###
PUT http://localhost:3001/daysales/5f7d8c5aefa7c5f7d8c5aefa7 HTTP/1.1
Content-Type: application/json

{
    "id_db": "5f7d8c5aefa7c5f7d8c5aefa7",
    "name": "item2",
    "price": 15,
    "units": 4
}
