###
POST http://localhost:3001/product HTTP/1.1
Content-Type: application/json

{
  "name": "Cerveza 1/2 Cero",
  "description": "Cerveza de 250 ml",
  "price": 30,
  "image": "https://m.media-amazon.com/images/I/81UITv4OpWL._AC_SY445_.jpg",
  "units" : 10,
  "category": "63acbba13bd411f44a60d04f"
}

###
GET http://localhost:3001/product  HTTP/1.1


###
GET http://localhost:3001/product/63acbdfc64e9ea4c89edf6cf  HTTP/1.1


###
PUT http://localhost:3001/product/63acc1dcd344f1e651a22937 HTTP/1.1
Content-Type: application/json

{
  
  "image": "https://m.media-amazon.com/images/I/61vYdM6juBL.jpg"
}

###
DELETE  http://localhost:3001/product/63acc11bd344f1e651a2292a  HTTP/1.1