###
POST http://localhost:3001/product HTTP/1.1
Content-Type: application/json

{
  "name": "Chaka Fresa 1 LT",
  "description": "Bebida sabor Fresa.",
  "ingredients": [
    "Zaverich",
    "Granadina",
    "Curazao"
  ],
  "price": 80,
  "image": "https://juegoscocinarpasteleria.org/wp-content/uploads/2020/03/1583412544_780_Como-hacer-una-bebida-roja-blanca-y-azul-con-capas.jpg",
  "units" : 10,
  "category": "640413c15466ad40d1e84c19"
}

###
GET http://localhost:3001/product  HTTP/1.1


###
GET http://localhost:3001/product/63acbdfc64e9ea4c89edf6cf  HTTP/1.1


###
PUT http://localhost:3001/product/6404c989d3e2af7f53988ce7 HTTP/1.1
Content-Type: application/json

{
  "description": "Bebida sabor Mazapan."
}

###
DELETE  http://localhost:3001/product/63acc11bd344f1e651a2292a  HTTP/1.1