###
POST http://localhost:3001/user HTTP/1.1
Content-Type: application/json

{"firstName":"Yolatzin",
"lastName":"dsafdfas",
"email":"fdsafsdfsad@gmail.com",
"username":"yolatzin",
"password":"5555",
"role":"admin",
"avatar":"2",
"age":24}

###
GET http://localhost:3001/user  HTTP/1.1


###
GET http://localhost:3001/user/63ac6fadb9a3f706d4496324  HTTP/1.1


###
PUT http://localhost:3001/user/63ac790c21eadc689bf24a5b HTTP/1.1
Content-Type: application/json

{
    "email": "dragodofb@gmail.com",
    "username": "drago",
    "password": "5555"
  }

###
DELETE  http://localhost:3001/user/63ac6fadb9a3f706d4496324  HTTP/1.1